import type { HomePageConfig } from '@/app/_components/home/type';

export const homeConfig: HomePageConfig = {
    welcome: {
        title: '欢迎朋友',
        colorTitle: '行路客的小站',
        content: `本站为个人博客，记录个人学习和生活，欢迎朋友们来访，一起交流学习，共同进步`,
    },
    video: {
        image: 'url(xxxx)',
        video: 'xxxx',
    },
    list: {
        first: {
            data: [
  { text: "勇气是抵抗恐惧、掌控恐惧，而不是没有恐惧。— 马克·吐温" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill" },
  { text: "失敗は成功の母。— 日本谚语（失败是成功之母）" },
  { text: "포기하지 마세요. 끝까지 해보세요. — 한국 속담（不要放弃，坚持到底）" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día. — Robert Collier" },
  { text: "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. — Albert Schweitzer" },
  { text: "每一个伟大的梦想，都始于一个勇敢的心。" },
  { text: "Believe you can and you're halfway there. — Theodore Roosevelt" },
  { text: "夢を持ち続けることが人生の力になる。— Japanese proverb" },
  { text: "당신의 한 걸음이 천리를 만든다. — Korean saying" },
  { text: "La vida es 10% lo que me ocurre y 90% cómo reacciono a ello. — Charles Swindoll" },
  { text: "Il n’y a qu’une façon d’échouer, c’est d’abandonner avant d’avoir réussi." },
  { text: "不要害怕慢，只怕停。" },
  { text: "Do what you can, with what you have, where you are." },
  { text: "石の上にも三年。— Perseverance prevails (Japanese proverb)" },
  { text: "시작이 반이다. — Korean proverb (开始就是成功的一半)" },
  { text: "No hay camino para la felicidad, la felicidad es el camino. — Buddha" },
  { text: "Qui ne tente rien n’a rien. — French proverb (不入虎穴，焉得虎子)" },
  { text: "千里之行，始于足下。" },
  { text: "The best way to predict the future is to create it." },
  { text: "継続は力なり。— Continuity is power (Japanese proverb)" },
  { text: "성공은 노력의 결과다. — Korean saying" },
  { text: "El fracaso es solo la oportunidad de comenzar de nuevo con más inteligencia. — Henry Ford" },
  { text: "La persévérance vient à bout de tout. — French proverb" },
  { text: "要想走得远，就要一步一个脚印。" },
  { text: "Great things never came from comfort zones." },
  { text: "夢を見るから人生は輝く。— Japanese proverb" },
  { text: "작은 습관이 큰 변화를 만든다. — Korean proverb" },
  { text: "La vida es corta, sonríe mientras aún tengas dientes." },
  { text: "Il faut toujours viser la lune, car même en cas d’échec on atterrit dans les étoiles." },
  { text: "心有多大，舞台就有多大。" },
  { text: "Don't watch the clock; do what it does. Keep going." },
  { text: "七転び八起き。— Fall seven times, stand up eight." },
  { text: "하루에 하나씩, 목표를 향해 나아가라. — Korean saying" },
  { text: "El que persevera, alcanza. — Spanish proverb" },
  { text: "Petit à petit, l’oiseau fait son nid. — French proverb" },
  { text: "失败不可怕，可怕的是从不尝试。" },
  { text: "It always seems impossible until it’s done. — Nelson Mandela" },
  { text: "努力は決して裏切らない。— Effort never betrays (Japanese saying)" },
  { text: "노력은 절대 배신하지 않는다. — Korean equivalent" },
  { text: "Cree en ti mismo y todo será posible." },
  { text: "Fais de ta vie un rêve, et d’un rêve, une réalité. — Antoine de Saint-Exupéry" },
  { text: "越努力，越幸运。" },
  { text: "Dream big. Work hard. Stay humble." },
  { text: "できると思えばできる。— You can do it if you think you can." },
  { text: "할 수 있다고 믿어라. — Believe you can." },
  { text: "Nunca es tarde para ser lo que podrías haber sido. — George Eliot" },
  { text: "Rien n’est impossible pour un cœur vaillant." },
  { text: "不经历风雨，怎能见彩虹？" },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you." },
  { text: "志を立てて以て万事の源となす。— Japanese proverb" },
  { text: "뜻이 있는 곳에 길이 있다. — Where there is a will, there is a way." },
  { text: "A la tercera va la vencida. — Spanish proverb" },
  { text: "C’est en forgeant qu’on devient forgeron." },
  { text: "每天进步一点点。" },
  { text: "The harder you work for something, the greater you’ll feel when you achieve it." },
  { text: "継続こそが力だ。— Perseverance is strength." },
  { text: "작은 성공이 큰 성공을 만든다. — Small success builds big success." },
  { text: "El único modo de hacer un gran trabajo es amar lo que haces. — Steve Jobs" },
  { text: "Rêver, c’est déjà le début du succès." },
  { text: "不怕慢，只怕站。" },
  { text: "Push yourself, because no one else is going to do it for you." },
  { text: "やればできる。— If you try, you can do it." },
  { text: "도전 없는 삶은 성장 없는 삶이다. — Without challenge, no growth." },
  { text: "Cada día es una nueva oportunidad para mejorar." },
  { text: "L’avenir appartient à ceux qui se lèvent tôt." },
  { text: "不要等待机会，要创造机会。" },
  { text: "Don’t limit your challenges. Challenge your limits." },
  { text: "今日という日は、残りの人生の最初の日。— Today is the first day of the rest of your life." },
  { text: "오늘이 바로 새로운 시작이다. — Today is a new start." },
  { text: "Hazlo ahora. A veces ‘después’ se convierte en ‘nunca’." },
  { text: "Agis comme s’il était impossible d’échouer. — Act as if failure were impossible." },
  { text: "让自己发光，而不是依附他人发光。" },
  { text: "You are stronger than you think." },
  { text: "笑う門には福来る。— Fortune comes to a smiling home." },
  { text: "웃으면 복이 온다. — Korean equivalent proverb." },
  { text: "Sigue tus sueños, ellos saben el camino." },
  { text: "Reste fidèle à toi-même, c’est ta plus grande force." },
  { text: "成功者不是从不失败，而是永不放弃。" },
  { text: "You don’t have to be perfect to be amazing." },
  { text: "初心を忘れずに。— Never forget your original intention." },
  { text: "초심을 잃지 말자. — Stay true to your beginnings." },
  { text: "La paciencia es amarga, pero su fruto es dulce. — Rousseau" },
  { text: "Chaque jour compte. — Every day matters." },
  { text: "人生没有白走的路，每一步都算数。" },
  { text: "Be fearless in the pursuit of what sets your soul on fire." },
  { text: "成せばなる。— Where there’s a will, there’s a way." },
  { text: "끝까지 해내는 것이 진짜 용기다. — Real courage is finishing." },
  { text: "La fuerza no proviene de la capacidad, sino de la voluntad." },
  { text: "La vie commence là où commence ton courage." },
  { text: "活着就有希望。" },
  { text: "You only fail when you stop trying." },
  { text: "夢は逃げない。逃げるのはいつも自分だ。— Dreams don’t run away, you do." },
  { text: "꿈은 도망가지 않는다. 포기하지 말자. — Dreams don’t run away." },
  { text: "El optimismo es la fe que conduce al logro. — Helen Keller" },
  { text: "L’espoir fait vivre. — Hope keeps us alive." },
  { text: "心中有光，何惧黑暗。" },
]

        },
        second: {
            title: 'icon',
            data: [
              {
                id: 'github',
                title: 'GitHub',
                href: 'https://github.com/yourname',
                external: true,
              },
              {
                id: 'twitter',
                title: 'Twitter',
                href: 'https://twitter.com/yourname',
                external: true,
              },
              {
                id: 'linkedin',
                title: 'LinkedIn',
                href: 'https://www.linkedin.com/in/yourname',
                external: true,
              },
              {
                id: 'mail',
                title: 'Email',
                href: 'mailto:you@example.com',
                external: true,
              },
              {
                id: 'rss',
                title: 'RSS Feed',
                href: '/rss.xml',
                external: false,
              },
            ]
        },
    },
    typed: [
        `🤝 欢迎来到行路客的小站！👋
        这里是记录技术思考与生活感悟的角落，每一篇文章都源于真实的探索与体验。
        无论是代码的乐趣、旅途的风景，还是生活的点滴，我都希望能与您分享。
        感谢您的停留，愿这里能为您带来一点灵感或温暖！
        
        ~`
    ],
    timeline: [
        {
            title: '未来',
            content: `当创业或兼职的收入足以覆盖主业时，会放弃主业，全力投入，路虽远，行必至~~~~~`,
        },
    
        {
            title: '至今',
            content: `尝试个人创业（内容保密，成果时零食钱和车辆的油费足够了），同时接一些远程工作兼职，主业也做着`,
        },
        {
            title: '2024.01',
            content: `加入Titan，负责无人驾驶数据接入数据处理工作，同时接触到远程工作的信息，开始尝试兼职远程工作`,
        },
        {
            title: '2023.12',
            content: `部门解散`,
        },
        {
            title: '2022.10',
            content: `加入中科大脑，负责智慧城市研发工作，UAV集群城市监控的项目整体负责，手下有3位外包来的兄弟`,
        },
        {
            title: '2022.09',
            content: `企业业务出现问题，且被其他公司收购拿大礼包`,
        },
        {
            title: '2022.04',
            content: `加入SanBao，负责后端研发`,
        },
        {
            title: '2022.03.22',
            content: `项目交付，奖金拖欠，沟通数次无果，没法向手下兄弟交待（打鸡血疯狂加班），也没法向自己交待`,
        },
        {
            title: '2021.02',
            content: `入职江北某研究所，谨言慎行，3个月后，升职加薪，收入上了20。成了部门老二，老大常年出差，我就大权在握了，手下管着9位牛马兄弟`,
        },
        {
            title: '2021.01',
            content: `开大会时技术层面提问让主持会议的Lead下不来，后续么，穿了不少鞋子。总结下教训，辞职了`,
        },
        {
            title: '2020.11.10',
            content: `入职中通服，钱多事少离家近，工作稳定，美滋滋`,
        },
        { title: '2020.08.01', 
          content: 'feel翅膀硬了，感觉良好，同时收到阿里P6岗位的offer邮件，验证了我的想法，索性当月提交了辞呈回南京发展' },
        {
            title: '2018.07.25',
            content: '入行第一个大项目开始，MES类项目，人机交互生产，目标千人以上的工厂信息化、数字化，后面的项目都是在这个基础上重构或者抽象一些专属工具',
        },
        { title: '2018.04.23', 
          content: '集团组件物联网研发团队，恰巧打小对计算机兴趣浓烈，申请了内部转岗，转职成功' },
        {
            title: '2017.06.20',
            content: '学生生涯结束，因为自动化专业，NX做的一手好图，不出意外的成为了一名机械助理工程师，加入Jack负责画图和首件的生产监测',
        },
    ],
};
